
//! Autogenerated weights for `pallet_model_voting`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2024-06-22, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Bob`, CPU: `11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/node-template
// benchmark
// pallet
// --chain=dev
// --wasm-execution=compiled
// --pallet=pallet_model_voting
// --extrinsic=*
// --steps=50
// --repeat=20
// --output=pallets/model-voting/src/weights.rs
// --template
// ./.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_model_voting`.
pub trait WeightInfo {
	fn propose() -> Weight;
	fn cast_vote() -> Weight;
	fn cancel() -> Weight;
}

/// Weights for `pallet_model_voting` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `SubnetVoting::ActiveProposals` (r:1 w:1)
	/// Proof: `SubnetVoting::ActiveProposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubnetVoting::PropCount` (r:1 w:1)
	/// Proof: `SubnetVoting::PropCount` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::SubnetPaths` (r:1 w:0)
	/// Proof: `Network::SubnetPaths` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubnetVoting::PropsPathStatus` (r:1 w:1)
	/// Proof: `SubnetVoting::PropsPathStatus` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::MinSubnetNodes` (r:1 w:0)
	/// Proof: `Network::MinSubnetNodes` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::MaxSubnetNodes` (r:1 w:0)
	/// Proof: `Network::MaxSubnetNodes` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::MinStakeBalance` (r:1 w:0)
	/// Proof: `Network::MinStakeBalance` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:13 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Network::ConsensusBlocksInterval` (r:1 w:0)
	/// Proof: `Network::ConsensusBlocksInterval` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::MinRequiredNodeConsensusInclusionEpochs` (r:1 w:0)
	/// Proof: `Network::MinRequiredNodeConsensusInclusionEpochs` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::SubnetNodesData` (r:1 w:0)
	/// Proof: `Network::SubnetNodesData` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::SubnetPerNodeInitCost` (r:1 w:0)
	/// Proof: `Network::SubnetPerNodeInitCost` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubnetVoting::VotesBalance` (r:0 w:1)
	/// Proof: `SubnetVoting::VotesBalance` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubnetVoting::Proposals` (r:0 w:1)
	/// Proof: `SubnetVoting::Proposals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn propose() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3085`
		//  Estimated: `34829`
		// Minimum execution time: 122_980_000 picoseconds.
		Weight::from_parts(143_869_000, 34829)
			.saturating_add(T::DbWeight::get().reads(24_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `SubnetVoting::Proposals` (r:1 w:0)
	/// Proof: `SubnetVoting::Proposals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `SubnetVoting::NodeVotePremium` (r:1 w:0)
	/// Proof: `SubnetVoting::NodeVotePremium` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubnetVoting::Votes` (r:1 w:1)
	/// Proof: `SubnetVoting::Votes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubnetVoting::VotesBalance` (r:0 w:1)
	/// Proof: `SubnetVoting::VotesBalance` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn cast_vote() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1440`
		//  Estimated: `4905`
		// Minimum execution time: 48_022_000 picoseconds.
		Weight::from_parts(55_874_000, 4905)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `SubnetVoting::Proposals` (r:1 w:1)
	/// Proof: `SubnetVoting::Proposals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubnetVoting::ActiveProposals` (r:1 w:1)
	/// Proof: `SubnetVoting::ActiveProposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn cancel() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1338`
		//  Estimated: `4803`
		// Minimum execution time: 26_545_000 picoseconds.
		Weight::from_parts(28_805_000, 4803)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `SubnetVoting::ActiveProposals` (r:1 w:1)
	/// Proof: `SubnetVoting::ActiveProposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubnetVoting::PropCount` (r:1 w:1)
	/// Proof: `SubnetVoting::PropCount` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::SubnetPaths` (r:1 w:0)
	/// Proof: `Network::SubnetPaths` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubnetVoting::PropsPathStatus` (r:1 w:1)
	/// Proof: `SubnetVoting::PropsPathStatus` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::MinSubnetNodes` (r:1 w:0)
	/// Proof: `Network::MinSubnetNodes` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::MaxSubnetNodes` (r:1 w:0)
	/// Proof: `Network::MaxSubnetNodes` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::MinStakeBalance` (r:1 w:0)
	/// Proof: `Network::MinStakeBalance` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:13 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Network::ConsensusBlocksInterval` (r:1 w:0)
	/// Proof: `Network::ConsensusBlocksInterval` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::MinRequiredNodeConsensusInclusionEpochs` (r:1 w:0)
	/// Proof: `Network::MinRequiredNodeConsensusInclusionEpochs` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::SubnetNodesData` (r:1 w:0)
	/// Proof: `Network::SubnetNodesData` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::SubnetPerNodeInitCost` (r:1 w:0)
	/// Proof: `Network::SubnetPerNodeInitCost` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubnetVoting::VotesBalance` (r:0 w:1)
	/// Proof: `SubnetVoting::VotesBalance` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubnetVoting::Proposals` (r:0 w:1)
	/// Proof: `SubnetVoting::Proposals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn propose() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3085`
		//  Estimated: `34829`
		// Minimum execution time: 122_980_000 picoseconds.
		Weight::from_parts(143_869_000, 34829)
			.saturating_add(RocksDbWeight::get().reads(24_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: `SubnetVoting::Proposals` (r:1 w:0)
	/// Proof: `SubnetVoting::Proposals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `SubnetVoting::NodeVotePremium` (r:1 w:0)
	/// Proof: `SubnetVoting::NodeVotePremium` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubnetVoting::Votes` (r:1 w:1)
	/// Proof: `SubnetVoting::Votes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubnetVoting::VotesBalance` (r:0 w:1)
	/// Proof: `SubnetVoting::VotesBalance` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn cast_vote() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1440`
		//  Estimated: `4905`
		// Minimum execution time: 48_022_000 picoseconds.
		Weight::from_parts(55_874_000, 4905)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `SubnetVoting::Proposals` (r:1 w:1)
	/// Proof: `SubnetVoting::Proposals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubnetVoting::ActiveProposals` (r:1 w:1)
	/// Proof: `SubnetVoting::ActiveProposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn cancel() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1338`
		//  Estimated: `4803`
		// Minimum execution time: 26_545_000 picoseconds.
		Weight::from_parts(28_805_000, 4803)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
}