
//! Autogenerated weights for `pallet_network`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2024-04-07, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Bob`, CPU: `11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/node-template
// benchmark
// pallet
// --chain=dev
// --wasm-execution=compiled
// --pallet=pallet_network
// --extrinsic=*
// --steps=50
// --repeat=20
// --output=pallets/network/src/weights.rs
// --template
// ./.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_network`.
pub trait WeightInfo {
	fn submit_consensus_data() -> Weight;
	fn add_model() -> Weight;
	fn add_model_peer() -> Weight;
	fn remove_model_peer() -> Weight;
	fn update_port() -> Weight;
	fn add_to_stake() -> Weight;
	fn remove_stake() -> Weight;
	fn form_consensus_data() -> Weight;
	fn generate_emissions_max_model() -> Weight;
	fn generate_emissions_emissions_weights() -> Weight;
	fn form_consensus_no_consensus_weight_test() -> Weight;
}

/// Weights for `pallet_network` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Network::ConsensusBlocksInterval` (r:1 w:0)
	/// Proof: `Network::ConsensusBlocksInterval` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::MaxAccountPenaltyCount` (r:1 w:0)
	/// Proof: `Network::MaxAccountPenaltyCount` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::AccountPenaltyCount` (r:232 w:0)
	/// Proof: `Network::AccountPenaltyCount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::RemoveModelPeerEpochPercentage` (r:1 w:0)
	/// Proof: `Network::RemoveModelPeerEpochPercentage` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelsData` (r:1 w:0)
	/// Proof: `Network::ModelsData` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelPeersData` (r:233 w:0)
	/// Proof: `Network::ModelPeersData` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::TotalModelPeers` (r:1 w:0)
	/// Proof: `Network::TotalModelPeers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::PeerConsensusEpochSubmitted` (r:1 w:1)
	/// Proof: `Network::PeerConsensusEpochSubmitted` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::MinRequiredModelConsensusSubmitEpochs` (r:1 w:0)
	/// Proof: `Network::MinRequiredModelConsensusSubmitEpochs` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::MinRequiredPeerConsensusSubmitEpochs` (r:1 w:0)
	/// Proof: `Network::MinRequiredPeerConsensusSubmitEpochs` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::MinModelPeers` (r:1 w:0)
	/// Proof: `Network::MinModelPeers` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::MinRequiredPeerConsensusInclusionEpochs` (r:1 w:0)
	/// Proof: `Network::MinRequiredPeerConsensusInclusionEpochs` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelPeerConsensusResults` (r:232 w:232)
	/// Proof: `Network::ModelPeerConsensusResults` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::PeerConsensusEpochUnconfirmed` (r:1 w:0)
	/// Proof: `Network::PeerConsensusEpochUnconfirmed` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelTotalConsensusSubmits` (r:1 w:1)
	/// Proof: `Network::ModelTotalConsensusSubmits` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn submit_consensus_data() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `35818`
		//  Estimated: `613483`
		// Minimum execution time: 9_317_343_000 picoseconds.
		Weight::from_parts(9_909_682_000, 613483)
			.saturating_add(T::DbWeight::get().reads(709_u64))
			.saturating_add(T::DbWeight::get().writes(234_u64))
	}
	/// Storage: `Network::ModelPaths` (r:1 w:1)
	/// Proof: `Network::ModelPaths` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelActivated` (r:1 w:0)
	/// Proof: `Network::ModelActivated` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelsData` (r:1 w:1)
	/// Proof: `Network::ModelsData` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::MaxModels` (r:1 w:0)
	/// Proof: `Network::MaxModels` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ConsensusBlocksInterval` (r:1 w:0)
	/// Proof: `Network::ConsensusBlocksInterval` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::MinRequiredPeerConsensusInclusionEpochs` (r:1 w:0)
	/// Proof: `Network::MinRequiredPeerConsensusInclusionEpochs` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelPeersData` (r:1 w:0)
	/// Proof: `Network::ModelPeersData` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelPerPeerInitCost` (r:1 w:0)
	/// Proof: `Network::ModelPerPeerInitCost` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::TotalModels` (r:1 w:1)
	/// Proof: `Network::TotalModels` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn add_model() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `151`
		//  Estimated: `3616`
		// Minimum execution time: 37_175_000 picoseconds.
		Weight::from_parts(38_326_000, 3616)
			.saturating_add(T::DbWeight::get().reads(9_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Network::ConsensusBlocksInterval` (r:1 w:0)
	/// Proof: `Network::ConsensusBlocksInterval` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelsData` (r:1 w:0)
	/// Proof: `Network::ModelsData` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::MaxAccountPenaltyCount` (r:1 w:0)
	/// Proof: `Network::MaxAccountPenaltyCount` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::AccountPenaltyCount` (r:1 w:0)
	/// Proof: `Network::AccountPenaltyCount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::TotalModelPeers` (r:1 w:1)
	/// Proof: `Network::TotalModelPeers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::MaxModelPeers` (r:1 w:0)
	/// Proof: `Network::MaxModelPeers` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelPeersData` (r:1 w:1)
	/// Proof: `Network::ModelPeersData` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelPeerAccount` (r:1 w:1)
	/// Proof: `Network::ModelPeerAccount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::AccountModelStake` (r:1 w:1)
	/// Proof: `Network::AccountModelStake` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::MinStakeBalance` (r:1 w:0)
	/// Proof: `Network::MinStakeBalance` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::MaxStakeBalance` (r:1 w:0)
	/// Proof: `Network::MaxStakeBalance` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::LastTxBlock` (r:1 w:1)
	/// Proof: `Network::LastTxBlock` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::TxRateLimit` (r:1 w:0)
	/// Proof: `Network::TxRateLimit` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::TotalAccountStake` (r:1 w:1)
	/// Proof: `Network::TotalAccountStake` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::TotalModelStake` (r:1 w:1)
	/// Proof: `Network::TotalModelStake` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::TotalStake` (r:1 w:1)
	/// Proof: `Network::TotalStake` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelAccount` (r:1 w:1)
	/// Proof: `Network::ModelAccount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::AccountModels` (r:1 w:1)
	/// Proof: `Network::AccountModels` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn add_model_peer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `500`
		//  Estimated: `3965`
		// Minimum execution time: 87_892_000 picoseconds.
		Weight::from_parts(91_808_000, 3965)
			.saturating_add(T::DbWeight::get().reads(18_u64))
			.saturating_add(T::DbWeight::get().writes(10_u64))
	}
	/// Storage: `Network::ConsensusBlocksInterval` (r:1 w:0)
	/// Proof: `Network::ConsensusBlocksInterval` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelsData` (r:1 w:0)
	/// Proof: `Network::ModelsData` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelPeersData` (r:1 w:1)
	/// Proof: `Network::ModelPeersData` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::MinRequiredPeerConsensusInclusionEpochs` (r:1 w:0)
	/// Proof: `Network::MinRequiredPeerConsensusInclusionEpochs` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelAccount` (r:1 w:1)
	/// Proof: `Network::ModelAccount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::TotalModelPeers` (r:1 w:1)
	/// Proof: `Network::TotalModelPeers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::AccountModels` (r:1 w:0)
	/// Proof: `Network::AccountModels` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelPeerConsensusResults` (r:0 w:1)
	/// Proof: `Network::ModelPeerConsensusResults` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelPeerAccount` (r:0 w:1)
	/// Proof: `Network::ModelPeerAccount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn remove_model_peer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `782`
		//  Estimated: `4247`
		// Minimum execution time: 45_742_000 picoseconds.
		Weight::from_parts(48_522_000, 4247)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `Network::ModelsData` (r:1 w:0)
	/// Proof: `Network::ModelsData` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelPeersData` (r:1 w:1)
	/// Proof: `Network::ModelPeersData` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn update_port() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `639`
		//  Estimated: `4104`
		// Minimum execution time: 18_133_000 picoseconds.
		Weight::from_parts(19_542_000, 4104)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Network::ConsensusBlocksInterval` (r:1 w:0)
	/// Proof: `Network::ConsensusBlocksInterval` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelsData` (r:1 w:0)
	/// Proof: `Network::ModelsData` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelPeersData` (r:1 w:0)
	/// Proof: `Network::ModelPeersData` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::AccountModelStake` (r:1 w:1)
	/// Proof: `Network::AccountModelStake` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::MinStakeBalance` (r:1 w:0)
	/// Proof: `Network::MinStakeBalance` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::MaxStakeBalance` (r:1 w:0)
	/// Proof: `Network::MaxStakeBalance` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::LastTxBlock` (r:1 w:1)
	/// Proof: `Network::LastTxBlock` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::TxRateLimit` (r:1 w:0)
	/// Proof: `Network::TxRateLimit` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::TotalAccountStake` (r:1 w:1)
	/// Proof: `Network::TotalAccountStake` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::TotalModelStake` (r:1 w:1)
	/// Proof: `Network::TotalModelStake` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::TotalStake` (r:1 w:1)
	/// Proof: `Network::TotalStake` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn add_to_stake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1075`
		//  Estimated: `4540`
		// Minimum execution time: 71_412_000 picoseconds.
		Weight::from_parts(75_291_000, 4540)
			.saturating_add(T::DbWeight::get().reads(11_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `Network::ConsensusBlocksInterval` (r:1 w:0)
	/// Proof: `Network::ConsensusBlocksInterval` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelAccount` (r:1 w:0)
	/// Proof: `Network::ModelAccount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::MinRequiredUnstakeEpochs` (r:1 w:0)
	/// Proof: `Network::MinRequiredUnstakeEpochs` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelPeersData` (r:1 w:0)
	/// Proof: `Network::ModelPeersData` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::AccountModelStake` (r:1 w:1)
	/// Proof: `Network::AccountModelStake` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::MinStakeBalance` (r:1 w:0)
	/// Proof: `Network::MinStakeBalance` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::LastTxBlock` (r:1 w:1)
	/// Proof: `Network::LastTxBlock` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::TxRateLimit` (r:1 w:0)
	/// Proof: `Network::TxRateLimit` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::TotalAccountStake` (r:1 w:1)
	/// Proof: `Network::TotalAccountStake` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::TotalStake` (r:1 w:1)
	/// Proof: `Network::TotalStake` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::TotalModelStake` (r:1 w:1)
	/// Proof: `Network::TotalModelStake` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn remove_stake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1163`
		//  Estimated: `4628`
		// Minimum execution time: 70_162_000 picoseconds.
		Weight::from_parts(77_230_000, 4628)
			.saturating_add(T::DbWeight::get().reads(11_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `Network::ConsensusBlocksInterval` (r:1 w:0)
	/// Proof: `Network::ConsensusBlocksInterval` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::MaximumOutlierDeltaPercent` (r:1 w:0)
	/// Proof: `Network::MaximumOutlierDeltaPercent` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelPeerConsensusSubmitPercentRequirement` (r:1 w:0)
	/// Proof: `Network::ModelPeerConsensusSubmitPercentRequirement` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::MaxModelConsensusEpochsErrors` (r:1 w:0)
	/// Proof: `Network::MaxModelConsensusEpochsErrors` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::MinRequiredModelConsensusSubmitEpochs` (r:1 w:0)
	/// Proof: `Network::MinRequiredModelConsensusSubmitEpochs` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelConsensusUnconfirmedThreshold` (r:1 w:0)
	/// Proof: `Network::ModelConsensusUnconfirmedThreshold` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::MaxModelPeerSequentialConsensusNotSent` (r:1 w:0)
	/// Proof: `Network::MaxModelPeerSequentialConsensusNotSent` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelPeerSequentialConsensusSentThreshold` (r:1 w:0)
	/// Proof: `Network::ModelPeerSequentialConsensusSentThreshold` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::MinRequiredPeerConsensusSubmitEpochs` (r:1 w:0)
	/// Proof: `Network::MinRequiredPeerConsensusSubmitEpochs` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelsData` (r:65 w:0)
	/// Proof: `Network::ModelsData` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelConsensusEpochsErrors` (r:64 w:0)
	/// Proof: `Network::ModelConsensusEpochsErrors` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelTotalConsensusSubmits` (r:64 w:64)
	/// Proof: `Network::ModelTotalConsensusSubmits` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::TotalModelPeers` (r:64 w:0)
	/// Proof: `Network::TotalModelPeers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelConsensusEpochUnconfirmedCount` (r:64 w:64)
	/// Proof: `Network::ModelConsensusEpochUnconfirmedCount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelConsensusUnconfirmedSequentialEpochsCount` (r:64 w:0)
	/// Proof: `Network::ModelConsensusUnconfirmedSequentialEpochsCount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelPeerConsensusResults` (r:14912 w:14848)
	/// Proof: `Network::ModelPeerConsensusResults` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelPeersData` (r:14912 w:0)
	/// Proof: `Network::ModelPeersData` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::PeerRemovalThreshold` (r:1 w:0)
	/// Proof: `Network::PeerRemovalThreshold` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::PeerConsensusEpochSubmitted` (r:14848 w:14848)
	/// Proof: `Network::PeerConsensusEpochSubmitted` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelPeerSequentialConsensusNotSent` (r:14848 w:0)
	/// Proof: `Network::ModelPeerSequentialConsensusNotSent` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelPeerSequentialConsensusSent` (r:14848 w:14848)
	/// Proof: `Network::ModelPeerSequentialConsensusSent` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::MaxAccountPenaltyCount` (r:1 w:0)
	/// Proof: `Network::MaxAccountPenaltyCount` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::AccountPenaltyCount` (r:232 w:0)
	/// Proof: `Network::AccountPenaltyCount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelsInConsensus` (r:1 w:1)
	/// Proof: `Network::ModelsInConsensus` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn form_consensus_data() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `142689964`
		//  Estimated: `179598154`
		// Minimum execution time: 907_562_005_000 picoseconds.
		Weight::from_parts(941_937_646_000, 179598154)
			.saturating_add(T::DbWeight::get().reads(74997_u64))
			.saturating_add(T::DbWeight::get().writes(44673_u64))
	}
	/// Storage: `Network::ConsensusBlocksInterval` (r:1 w:0)
	/// Proof: `Network::ConsensusBlocksInterval` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::MaxStakeBalance` (r:1 w:0)
	/// Proof: `Network::MaxStakeBalance` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelsInConsensus` (r:1 w:1)
	/// Proof: `Network::ModelsInConsensus` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelPeerConsensusResults` (r:14913 w:14848)
	/// Proof: `Network::ModelPeerConsensusResults` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::AccountModelStake` (r:14848 w:14848)
	/// Proof: `Network::AccountModelStake` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::StakeVaultBalance` (r:1 w:1)
	/// Proof: `Network::StakeVaultBalance` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::StakeRewardWeight` (r:1 w:0)
	/// Proof: `Network::StakeRewardWeight` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::MaxModelRewardsWeight` (r:1 w:0)
	/// Proof: `Network::MaxModelRewardsWeight` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::TotalAccountStake` (r:232 w:232)
	/// Proof: `Network::TotalAccountStake` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::TotalModelStake` (r:64 w:64)
	/// Proof: `Network::TotalModelStake` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::TotalStake` (r:1 w:1)
	/// Proof: `Network::TotalStake` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn generate_emissions_max_model() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `140328477`
		//  Estimated: `177239142`
		// Minimum execution time: 959_752_658_000 picoseconds.
		Weight::from_parts(971_723_761_000, 177239142)
			.saturating_add(T::DbWeight::get().reads(30064_u64))
			.saturating_add(T::DbWeight::get().writes(29995_u64))
	}
	/// Storage: `Network::ConsensusBlocksInterval` (r:1 w:0)
	/// Proof: `Network::ConsensusBlocksInterval` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::MaxStakeBalance` (r:1 w:0)
	/// Proof: `Network::MaxStakeBalance` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelsInConsensus` (r:1 w:1)
	/// Proof: `Network::ModelsInConsensus` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelPeerConsensusResults` (r:14913 w:14848)
	/// Proof: `Network::ModelPeerConsensusResults` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::AccountModelStake` (r:14848 w:14848)
	/// Proof: `Network::AccountModelStake` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::StakeVaultBalance` (r:1 w:1)
	/// Proof: `Network::StakeVaultBalance` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::StakeRewardWeight` (r:1 w:0)
	/// Proof: `Network::StakeRewardWeight` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::MaxModelRewardsWeight` (r:1 w:0)
	/// Proof: `Network::MaxModelRewardsWeight` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::TotalAccountStake` (r:232 w:232)
	/// Proof: `Network::TotalAccountStake` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::TotalModelStake` (r:64 w:64)
	/// Proof: `Network::TotalModelStake` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::TotalStake` (r:1 w:1)
	/// Proof: `Network::TotalStake` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn generate_emissions_emissions_weights() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `140328477`
		//  Estimated: `177239142`
		// Minimum execution time: 881_021_845_000 picoseconds.
		Weight::from_parts(944_432_929_000, 177239142)
			.saturating_add(T::DbWeight::get().reads(30064_u64))
			.saturating_add(T::DbWeight::get().writes(29995_u64))
	}
	/// Storage: `Network::ConsensusBlocksInterval` (r:1 w:0)
	/// Proof: `Network::ConsensusBlocksInterval` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn form_consensus_no_consensus_weight_test() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `80`
		//  Estimated: `1565`
		// Minimum execution time: 6_395_000 picoseconds.
		Weight::from_parts(6_711_000, 1565)
			.saturating_add(T::DbWeight::get().reads(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `Network::ConsensusBlocksInterval` (r:1 w:0)
	/// Proof: `Network::ConsensusBlocksInterval` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::MaxAccountPenaltyCount` (r:1 w:0)
	/// Proof: `Network::MaxAccountPenaltyCount` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::AccountPenaltyCount` (r:232 w:0)
	/// Proof: `Network::AccountPenaltyCount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::RemoveModelPeerEpochPercentage` (r:1 w:0)
	/// Proof: `Network::RemoveModelPeerEpochPercentage` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelsData` (r:1 w:0)
	/// Proof: `Network::ModelsData` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelPeersData` (r:233 w:0)
	/// Proof: `Network::ModelPeersData` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::TotalModelPeers` (r:1 w:0)
	/// Proof: `Network::TotalModelPeers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::PeerConsensusEpochSubmitted` (r:1 w:1)
	/// Proof: `Network::PeerConsensusEpochSubmitted` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::MinRequiredModelConsensusSubmitEpochs` (r:1 w:0)
	/// Proof: `Network::MinRequiredModelConsensusSubmitEpochs` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::MinRequiredPeerConsensusSubmitEpochs` (r:1 w:0)
	/// Proof: `Network::MinRequiredPeerConsensusSubmitEpochs` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::MinModelPeers` (r:1 w:0)
	/// Proof: `Network::MinModelPeers` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::MinRequiredPeerConsensusInclusionEpochs` (r:1 w:0)
	/// Proof: `Network::MinRequiredPeerConsensusInclusionEpochs` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelPeerConsensusResults` (r:232 w:232)
	/// Proof: `Network::ModelPeerConsensusResults` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::PeerConsensusEpochUnconfirmed` (r:1 w:0)
	/// Proof: `Network::PeerConsensusEpochUnconfirmed` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelTotalConsensusSubmits` (r:1 w:1)
	/// Proof: `Network::ModelTotalConsensusSubmits` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn submit_consensus_data() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `35818`
		//  Estimated: `613483`
		// Minimum execution time: 9_317_343_000 picoseconds.
		Weight::from_parts(9_909_682_000, 613483)
			.saturating_add(RocksDbWeight::get().reads(709_u64))
			.saturating_add(RocksDbWeight::get().writes(234_u64))
	}
	/// Storage: `Network::ModelPaths` (r:1 w:1)
	/// Proof: `Network::ModelPaths` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelActivated` (r:1 w:0)
	/// Proof: `Network::ModelActivated` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelsData` (r:1 w:1)
	/// Proof: `Network::ModelsData` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::MaxModels` (r:1 w:0)
	/// Proof: `Network::MaxModels` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ConsensusBlocksInterval` (r:1 w:0)
	/// Proof: `Network::ConsensusBlocksInterval` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::MinRequiredPeerConsensusInclusionEpochs` (r:1 w:0)
	/// Proof: `Network::MinRequiredPeerConsensusInclusionEpochs` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelPeersData` (r:1 w:0)
	/// Proof: `Network::ModelPeersData` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelPerPeerInitCost` (r:1 w:0)
	/// Proof: `Network::ModelPerPeerInitCost` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::TotalModels` (r:1 w:1)
	/// Proof: `Network::TotalModels` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn add_model() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `151`
		//  Estimated: `3616`
		// Minimum execution time: 37_175_000 picoseconds.
		Weight::from_parts(38_326_000, 3616)
			.saturating_add(RocksDbWeight::get().reads(9_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `Network::ConsensusBlocksInterval` (r:1 w:0)
	/// Proof: `Network::ConsensusBlocksInterval` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelsData` (r:1 w:0)
	/// Proof: `Network::ModelsData` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::MaxAccountPenaltyCount` (r:1 w:0)
	/// Proof: `Network::MaxAccountPenaltyCount` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::AccountPenaltyCount` (r:1 w:0)
	/// Proof: `Network::AccountPenaltyCount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::TotalModelPeers` (r:1 w:1)
	/// Proof: `Network::TotalModelPeers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::MaxModelPeers` (r:1 w:0)
	/// Proof: `Network::MaxModelPeers` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelPeersData` (r:1 w:1)
	/// Proof: `Network::ModelPeersData` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelPeerAccount` (r:1 w:1)
	/// Proof: `Network::ModelPeerAccount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::AccountModelStake` (r:1 w:1)
	/// Proof: `Network::AccountModelStake` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::MinStakeBalance` (r:1 w:0)
	/// Proof: `Network::MinStakeBalance` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::MaxStakeBalance` (r:1 w:0)
	/// Proof: `Network::MaxStakeBalance` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::LastTxBlock` (r:1 w:1)
	/// Proof: `Network::LastTxBlock` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::TxRateLimit` (r:1 w:0)
	/// Proof: `Network::TxRateLimit` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::TotalAccountStake` (r:1 w:1)
	/// Proof: `Network::TotalAccountStake` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::TotalModelStake` (r:1 w:1)
	/// Proof: `Network::TotalModelStake` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::TotalStake` (r:1 w:1)
	/// Proof: `Network::TotalStake` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelAccount` (r:1 w:1)
	/// Proof: `Network::ModelAccount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::AccountModels` (r:1 w:1)
	/// Proof: `Network::AccountModels` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn add_model_peer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `500`
		//  Estimated: `3965`
		// Minimum execution time: 87_892_000 picoseconds.
		Weight::from_parts(91_808_000, 3965)
			.saturating_add(RocksDbWeight::get().reads(18_u64))
			.saturating_add(RocksDbWeight::get().writes(10_u64))
	}
	/// Storage: `Network::ConsensusBlocksInterval` (r:1 w:0)
	/// Proof: `Network::ConsensusBlocksInterval` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelsData` (r:1 w:0)
	/// Proof: `Network::ModelsData` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelPeersData` (r:1 w:1)
	/// Proof: `Network::ModelPeersData` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::MinRequiredPeerConsensusInclusionEpochs` (r:1 w:0)
	/// Proof: `Network::MinRequiredPeerConsensusInclusionEpochs` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelAccount` (r:1 w:1)
	/// Proof: `Network::ModelAccount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::TotalModelPeers` (r:1 w:1)
	/// Proof: `Network::TotalModelPeers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::AccountModels` (r:1 w:0)
	/// Proof: `Network::AccountModels` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelPeerConsensusResults` (r:0 w:1)
	/// Proof: `Network::ModelPeerConsensusResults` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelPeerAccount` (r:0 w:1)
	/// Proof: `Network::ModelPeerAccount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn remove_model_peer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `782`
		//  Estimated: `4247`
		// Minimum execution time: 45_742_000 picoseconds.
		Weight::from_parts(48_522_000, 4247)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: `Network::ModelsData` (r:1 w:0)
	/// Proof: `Network::ModelsData` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelPeersData` (r:1 w:1)
	/// Proof: `Network::ModelPeersData` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn update_port() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `639`
		//  Estimated: `4104`
		// Minimum execution time: 18_133_000 picoseconds.
		Weight::from_parts(19_542_000, 4104)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Network::ConsensusBlocksInterval` (r:1 w:0)
	/// Proof: `Network::ConsensusBlocksInterval` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelsData` (r:1 w:0)
	/// Proof: `Network::ModelsData` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelPeersData` (r:1 w:0)
	/// Proof: `Network::ModelPeersData` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::AccountModelStake` (r:1 w:1)
	/// Proof: `Network::AccountModelStake` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::MinStakeBalance` (r:1 w:0)
	/// Proof: `Network::MinStakeBalance` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::MaxStakeBalance` (r:1 w:0)
	/// Proof: `Network::MaxStakeBalance` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::LastTxBlock` (r:1 w:1)
	/// Proof: `Network::LastTxBlock` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::TxRateLimit` (r:1 w:0)
	/// Proof: `Network::TxRateLimit` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::TotalAccountStake` (r:1 w:1)
	/// Proof: `Network::TotalAccountStake` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::TotalModelStake` (r:1 w:1)
	/// Proof: `Network::TotalModelStake` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::TotalStake` (r:1 w:1)
	/// Proof: `Network::TotalStake` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn add_to_stake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1075`
		//  Estimated: `4540`
		// Minimum execution time: 71_412_000 picoseconds.
		Weight::from_parts(75_291_000, 4540)
			.saturating_add(RocksDbWeight::get().reads(11_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: `Network::ConsensusBlocksInterval` (r:1 w:0)
	/// Proof: `Network::ConsensusBlocksInterval` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelAccount` (r:1 w:0)
	/// Proof: `Network::ModelAccount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::MinRequiredUnstakeEpochs` (r:1 w:0)
	/// Proof: `Network::MinRequiredUnstakeEpochs` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelPeersData` (r:1 w:0)
	/// Proof: `Network::ModelPeersData` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::AccountModelStake` (r:1 w:1)
	/// Proof: `Network::AccountModelStake` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::MinStakeBalance` (r:1 w:0)
	/// Proof: `Network::MinStakeBalance` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::LastTxBlock` (r:1 w:1)
	/// Proof: `Network::LastTxBlock` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::TxRateLimit` (r:1 w:0)
	/// Proof: `Network::TxRateLimit` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::TotalAccountStake` (r:1 w:1)
	/// Proof: `Network::TotalAccountStake` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::TotalStake` (r:1 w:1)
	/// Proof: `Network::TotalStake` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::TotalModelStake` (r:1 w:1)
	/// Proof: `Network::TotalModelStake` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn remove_stake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1163`
		//  Estimated: `4628`
		// Minimum execution time: 70_162_000 picoseconds.
		Weight::from_parts(77_230_000, 4628)
			.saturating_add(RocksDbWeight::get().reads(11_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: `Network::ConsensusBlocksInterval` (r:1 w:0)
	/// Proof: `Network::ConsensusBlocksInterval` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::MaximumOutlierDeltaPercent` (r:1 w:0)
	/// Proof: `Network::MaximumOutlierDeltaPercent` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelPeerConsensusSubmitPercentRequirement` (r:1 w:0)
	/// Proof: `Network::ModelPeerConsensusSubmitPercentRequirement` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::MaxModelConsensusEpochsErrors` (r:1 w:0)
	/// Proof: `Network::MaxModelConsensusEpochsErrors` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::MinRequiredModelConsensusSubmitEpochs` (r:1 w:0)
	/// Proof: `Network::MinRequiredModelConsensusSubmitEpochs` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelConsensusUnconfirmedThreshold` (r:1 w:0)
	/// Proof: `Network::ModelConsensusUnconfirmedThreshold` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::MaxModelPeerSequentialConsensusNotSent` (r:1 w:0)
	/// Proof: `Network::MaxModelPeerSequentialConsensusNotSent` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelPeerSequentialConsensusSentThreshold` (r:1 w:0)
	/// Proof: `Network::ModelPeerSequentialConsensusSentThreshold` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::MinRequiredPeerConsensusSubmitEpochs` (r:1 w:0)
	/// Proof: `Network::MinRequiredPeerConsensusSubmitEpochs` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelsData` (r:65 w:0)
	/// Proof: `Network::ModelsData` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelConsensusEpochsErrors` (r:64 w:0)
	/// Proof: `Network::ModelConsensusEpochsErrors` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelTotalConsensusSubmits` (r:64 w:64)
	/// Proof: `Network::ModelTotalConsensusSubmits` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::TotalModelPeers` (r:64 w:0)
	/// Proof: `Network::TotalModelPeers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelConsensusEpochUnconfirmedCount` (r:64 w:64)
	/// Proof: `Network::ModelConsensusEpochUnconfirmedCount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelConsensusUnconfirmedSequentialEpochsCount` (r:64 w:0)
	/// Proof: `Network::ModelConsensusUnconfirmedSequentialEpochsCount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelPeerConsensusResults` (r:14912 w:14848)
	/// Proof: `Network::ModelPeerConsensusResults` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelPeersData` (r:14912 w:0)
	/// Proof: `Network::ModelPeersData` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::PeerRemovalThreshold` (r:1 w:0)
	/// Proof: `Network::PeerRemovalThreshold` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::PeerConsensusEpochSubmitted` (r:14848 w:14848)
	/// Proof: `Network::PeerConsensusEpochSubmitted` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelPeerSequentialConsensusNotSent` (r:14848 w:0)
	/// Proof: `Network::ModelPeerSequentialConsensusNotSent` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelPeerSequentialConsensusSent` (r:14848 w:14848)
	/// Proof: `Network::ModelPeerSequentialConsensusSent` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::MaxAccountPenaltyCount` (r:1 w:0)
	/// Proof: `Network::MaxAccountPenaltyCount` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::AccountPenaltyCount` (r:232 w:0)
	/// Proof: `Network::AccountPenaltyCount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelsInConsensus` (r:1 w:1)
	/// Proof: `Network::ModelsInConsensus` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn form_consensus_data() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `142689964`
		//  Estimated: `179598154`
		// Minimum execution time: 907_562_005_000 picoseconds.
		Weight::from_parts(941_937_646_000, 179598154)
			.saturating_add(RocksDbWeight::get().reads(74997_u64))
			.saturating_add(RocksDbWeight::get().writes(44673_u64))
	}
	/// Storage: `Network::ConsensusBlocksInterval` (r:1 w:0)
	/// Proof: `Network::ConsensusBlocksInterval` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::MaxStakeBalance` (r:1 w:0)
	/// Proof: `Network::MaxStakeBalance` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelsInConsensus` (r:1 w:1)
	/// Proof: `Network::ModelsInConsensus` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelPeerConsensusResults` (r:14913 w:14848)
	/// Proof: `Network::ModelPeerConsensusResults` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::AccountModelStake` (r:14848 w:14848)
	/// Proof: `Network::AccountModelStake` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::StakeVaultBalance` (r:1 w:1)
	/// Proof: `Network::StakeVaultBalance` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::StakeRewardWeight` (r:1 w:0)
	/// Proof: `Network::StakeRewardWeight` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::MaxModelRewardsWeight` (r:1 w:0)
	/// Proof: `Network::MaxModelRewardsWeight` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::TotalAccountStake` (r:232 w:232)
	/// Proof: `Network::TotalAccountStake` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::TotalModelStake` (r:64 w:64)
	/// Proof: `Network::TotalModelStake` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::TotalStake` (r:1 w:1)
	/// Proof: `Network::TotalStake` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn generate_emissions_max_model() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `140328477`
		//  Estimated: `177239142`
		// Minimum execution time: 959_752_658_000 picoseconds.
		Weight::from_parts(971_723_761_000, 177239142)
			.saturating_add(RocksDbWeight::get().reads(30064_u64))
			.saturating_add(RocksDbWeight::get().writes(29995_u64))
	}
	/// Storage: `Network::ConsensusBlocksInterval` (r:1 w:0)
	/// Proof: `Network::ConsensusBlocksInterval` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::MaxStakeBalance` (r:1 w:0)
	/// Proof: `Network::MaxStakeBalance` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelsInConsensus` (r:1 w:1)
	/// Proof: `Network::ModelsInConsensus` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::ModelPeerConsensusResults` (r:14913 w:14848)
	/// Proof: `Network::ModelPeerConsensusResults` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::AccountModelStake` (r:14848 w:14848)
	/// Proof: `Network::AccountModelStake` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::StakeVaultBalance` (r:1 w:1)
	/// Proof: `Network::StakeVaultBalance` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::StakeRewardWeight` (r:1 w:0)
	/// Proof: `Network::StakeRewardWeight` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::MaxModelRewardsWeight` (r:1 w:0)
	/// Proof: `Network::MaxModelRewardsWeight` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::TotalAccountStake` (r:232 w:232)
	/// Proof: `Network::TotalAccountStake` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::TotalModelStake` (r:64 w:64)
	/// Proof: `Network::TotalModelStake` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::TotalStake` (r:1 w:1)
	/// Proof: `Network::TotalStake` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn generate_emissions_emissions_weights() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `140328477`
		//  Estimated: `177239142`
		// Minimum execution time: 881_021_845_000 picoseconds.
		Weight::from_parts(944_432_929_000, 177239142)
			.saturating_add(RocksDbWeight::get().reads(30064_u64))
			.saturating_add(RocksDbWeight::get().writes(29995_u64))
	}
	/// Storage: `Network::ConsensusBlocksInterval` (r:1 w:0)
	/// Proof: `Network::ConsensusBlocksInterval` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn form_consensus_no_consensus_weight_test() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `80`
		//  Estimated: `1565`
		// Minimum execution time: 6_395_000 picoseconds.
		Weight::from_parts(6_711_000, 1565)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
	}
}